[project]
name = "translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "streamlit==1.45.1",
    "imageio-ffmpeg==0.6.0",
    "openai-whisper==20231117",
    "pyannote-audio==3.1.1",
    "soundfile==0.12.1",
    "speechbrain==0.5.16",
    "deep-translator==1.11.4",
    "gtts==2.5.4",
    "torch==2.3.0",
    "torchaudio==2.3.0",
    "numpy==1.26.4",
    "python-dotenv==1.0.1",
    "huggingface-hub==0.23.5",
    "setuptools>=68",
]

[tool.uv]
no-build-isolation-package = ["openai-whisper"]

[tool.uv.extra-build-dependencies]
openai-whisper = ["setuptools"]
